---
version: '3'
services:

# START SERVICE ksqldb_server.base
  ksql_server:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.ksqldb_server.base:0.9.0
    environment: ['KSQL_BOOTSTRAP_SERVERS=${CONTECO_DC_KSQLDB_SERVER_KSQL_BOOTSTRAP_SERVERS}','KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE=true','KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE=true','KSQL_KSQL_SERVICE_ID=${CONTECO_DC_KSQLDB_SERVER_KSQL_KSQL_SERVICE_ID}'${CONTECO_DC_KSQLDB_SERVER_MODE}]
    command: []
    volumes: []
    ports: [${CONTECO_DC_KSQLDB_SERVER_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_KSQLDB_SERVER_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KSQLDB_SERVER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KSQLDB_SERVER_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KSQLDB_SERVER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_KSQLDB_SERVER_DEPLOY_PLACEMENT_CONSTRAINTS}]
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE ksqldb_server.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
